sudo: false
language: generic

matrix:
  include:
    - compiler: "GHC+Stack (OSX)"
      os: osx
      addons: {apt: {packages: [libgc-dev, libgmp-dev]}}
    # - compiler: "GHC+Stack (Linux)"
    #   addons: {apt: {packages: [libgc-dev, libgmp-dev]}}

before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install llvm-hs/homebrew-llvm/llvm-6.0 bdw-gc
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    export SIXTEN_ARGS="--llvm-config=$(brew --prefix llvm)/bin/llvm-config"
  else
    export SIXTEN_ARGS=""
  fi
- export STACK_FLAGS='-j 2 --no-terminal --skip-ghc-check'
- stack ${STACK_FLAGS} setup

script:
- stack test

cache:
  directories:
  - $HOME/.stack
