name: thrill
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Language
author: Xavier Denis
maintainer: xldenis@gmail.com
copyright: 2016 Author Here
license: BSD3
github: xldenis/thrill
homepage: http://github.com/xldenis/ill#readme
dependencies:
- megaparsec
- text
- base >=4.7 && <5
- mtl
- prettyprinter
- prettyprinter-ansi-terminal
- containers

library:
  ghc-options:
  - -fwarn-incomplete-uni-patterns
  - -fdiagnostics-color=always
  source-dirs: src
  other-modules: [Thrill.Prelude, Paths_thrill]
  dependencies:
  - free
  - comonad
  - lens
  - unordered-containers
  - bifunctors
  - llvm-hs
  - llvm-hs-pure
  - llvm-hs-pretty
  - transformers-compat
  - bytestring
  - semigroupoids
  - edit-distance
  default-extensions:
  - FlexibleContexts
  - NoImplicitPrelude
  - DeriveGeneric
  - FlexibleInstances
  - DeriveFunctor
  - DeriveTraversable
  - DeriveFoldable
executables:
  thrill:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - thrill
      - optparse-simple
      - llvm-hs
      - llvm-hs-pure
      - bytestring
      - temporary
      - process
      - terminal-size
    default-extensions:
    - ImplicitPrelude
tests:
  thrill-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - thrill
    - directory
    - hspec-megaparsec
    - filepath
    - comonad
    - template-haskell
data-files:
- assets/prelude.ill
- assets/rts.ll
