name: ill
version: '0.1.0.0'
synopsis: Initial project template from stack
description: Please see README.md
category: Language
author: Xavier Denis
maintainer: xldenis@gmail.com
copyright: 2016 Author Here
license: BSD3
github: xldenis/ill
homepage: http://github.com/xldenis/ill#readme
dependencies:
- megaparsec
- text
- base >=4.7 && <5
- mtl
- prettyprinter
- prettyprinter-ansi-terminal
- containers

library:
  ghc-options:
  - -fwarn-incomplete-uni-patterns
  - -fdiagnostics-color=always
  source-dirs: src
  dependencies:
  - free
  - comonad
  - lens
  - unordered-containers
  - bifunctors
  default-extensions: FlexibleContexts
executables:
  ill:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - ill
      - optparse-simple
tests:
  ill-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - ill
    - directory
    - hspec-megaparsec
    - filepath
    - comonad
    - template-haskell
data-files:
- assets/prelude.ill
