resolver: nightly-2017-10-31

packages:
- '.'
extra-deps:
- git: https://github.com/llvm-hs/llvm-hs.git
  commit: d80184eefe09d6a24df7c3268c53f279db00b44b
  subdirs:
    - llvm-hs
    - llvm-hs-pure
- git: https://github.com/llvm-hs/llvm-hs-pretty
  commit: ae349cce595fd94bdbf56689c2f2463f175db5ac

flags: {}
ghc-options:
  "$locals": -j #+RTS -A128m -n2m -RTS
